# Question :
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Well, After the observation Let's try to find the pattern in the sequence

# Here Even Sequence is 0, 2, 8, 34, 144, 610, 2584, 10946, 46368... and so on..

# Pattern that I found is that, the even sequence is the sum of 4th times of first term + second term in the sequence
# So, Nth term in the even sequence is 4 * (N-1)th term + (N-2)th term

# 8 = 4 * 2 + 0
# 34 = 4 * 8 + 2
# 144 = 4 * 34 + 8
# ... so on

N = 4000000 # The number below which we want to find the sum of even fibonacci numbers

Ans = 0 # The sum of even fibonacci numbers
first = 0 # The first term in the sequence
second = 2 # The second term in the sequence

while second <= N:
    Ans += second
    first, second = second, 4 * second + first
    
print(Ans)
# Answer : 4613732